const teams = [
  { id:'t1', name:'Team 01', color:'#7484fe', cash:1000, cv:0, pos:0, businesses:[] },
  { id:'t2', name:'Team 02', color:'#33ff67', cash:1000, cv:0, pos:0, businesses:[] },
  { id:'t3', name:'Team 03', color:'#ffc857', cash:1000, cv:0, pos:0, businesses:[] },
  { id:'t4', name:'Team 04', color:'#ff667b', cash:1000, cv:0, pos:0, businesses:[] },
  { id:'t5', name:'Team 05', color:'#b974fe', cash:1000, cv:0, pos:0, businesses:[] },
  { id:'t6', name:'Team 06', color:'#55d7e9', cash:1000, cv:0, pos:0, businesses:[] }
];
const businesses = [
  ['EdTech',200,150],['SaaS',300,180],['E-Commerce',300,180],['FinTech',400,200],['HealthTech',400,200],['AI / DeepTech',500,250],['DevTools / Infrastructure',300,190],['Cybersecurity',400,220],['CleanTech / Energy',500,240],['Robotics & IoT',500,250]
].map((x,i)=>({id:i,name:x[0],cost:x[1],baseCv:x[2],owner:null,level:0}));
const spaces = ['START','Pitch to Investors','EdTech','Bonus Card','SaaS','Crisis Card','E-Commerce','Action C','FinTech','Wildcard','HealthTech','Bonus Card','AI / DeepTech','Action D','DevTools / Infrastructure','Crisis Card','Cybersecurity','Bonus Card','CleanTech / Energy','Action B','Robotics & IoT','Crisis Card','Wildcard','Bonus Card'];
const state = { screen:'home', teams, teamCount:6, activeTeam:0, selectedTeam:0, seconds:3000, running:false, logs:[['09:00','Match ready. Waiting for all teams.']], phase:'waiting', selectedPlayer:0, pendingLanding:null, pendingSale:null, turnRolls:0, turnStartPos:0 };
const $ = (s)=>document.querySelector(s);
function money(n){ return `₹${Math.max(0,n).toLocaleString('en-IN')}`; }
function team(t){ return `<span class="team-name"><i class="team-color" style="background:${t.color}"></i>${t.name}</span>`; }
function header(role){ return `<header class="topbar"><div class="brand"><span class="brand-mark">S</span><span>STARTUPOLY <small>control room</small></span></div><div class="top-actions"><button class="btn ghost" onclick="goHome()">Switch view</button><span class="status-pill">Live console</span></div></header>`; }
function app(){ $('#app').innerHTML = state.screen==='home' ? home() : state.screen==='setup' ? setup() : state.screen==='admin' ? admin() : player(); }
function home(){ return `<div class="app-shell">${header('home')}<main class="content"><section class="hero"><div class="eyebrow">Equinox E-Summit 2K26 · Match console</div><h1>The live startup simulation, without the guesswork.</h1><p>One source of truth for the Game Master, Bank, Cards station and every team playing on the physical STARTUPOLY board.</p></section><div class="grid grid-2 role-grid"><button class="panel role-card" onclick="startSetup()"><div><div class="role-icon">◉</div><h2>Admin control room</h2><p class="muted">Run the match, resolve actions, update money and company value, and freeze the winner.</p></div><span class="arrow">↗</span></button><button class="panel role-card" onclick="openPlayer()"><div><div class="role-icon">⌁</div><h2>Player dashboard</h2><p class="muted">See only your team’s cash, company value, businesses, position and live events.</p></div><span class="arrow">↗</span></button></div></main></div>`; }
function setup(){ return `<div class="app-shell">${header()}<main class="content"><div class="setup-wrap"><div class="setup-title"><div><div class="eyebrow">New match setup</div><h1>Bring the teams in.</h1><p class="muted">The board is physical. This console keeps the state fair, fast and visible.</p></div><span class="status-pill">Waiting room</span></div><div class="panel"><div class="section-head"><div><h3>Teams checked in</h3><p>Minimum 5 · maximum 6 · 4–5 players per team</p></div><select class="select" style="width:120px" onchange="state.teamCount=+this.value;app()"><option value="5" ${state.teamCount===5?'selected':''}>5 teams</option><option value="6" ${state.teamCount===6?'selected':''}>6 teams</option></select></div><div class="team-setup">${teams.map((t,i)=>`<div class="team-chip" style="opacity:${i<state.teamCount?1:.35}"><i class="team-color" style="background:${t.color}"></i><span>${t.name}</span><span class="muted" style="margin-left:auto">${i<state.teamCount?'Ready':'Not playing'}</span></div>`).join('')}</div><div class="privacy-note">All teams start with ${money(1000)} cash, 0 Company Value and 0 businesses. Player access stays restricted to the team selected at sign-in.</div><div style="display:flex;justify-content:flex-end;margin-top:18px"><button class="btn green" onclick="beginMatch()">Move everyone to board →</button></div></div></div></main></div>`; }
function metrics(){ const active=teams.slice(0,state.teamCount), alive=active.filter(t=>t.cash>=0); return `<div class="grid grid-3"><div class="panel metric"><div class="label">Match clock</div><div class="value" id="clock">${clock()}</div></div><div class="panel metric"><div class="label">Active turn</div><div class="value">${teams[state.activeTeam].name}</div></div><div class="panel metric"><div class="label">Teams active</div><div class="value">${alive.length} <span class="muted" style="font-size:14px">/ ${state.teamCount}</span></div></div></div>`; }
function clock(){ const m=Math.floor(state.seconds/60).toString().padStart(2,'0'), s=(state.seconds%60).toString().padStart(2,'0'); return `${m}:${s}`; }
function admin(){ return `<div class="app-shell">${header()}<main class="content"><div class="section-head"><div><div class="eyebrow">Admin control room · Match 1</div><h1>Keep the board moving.</h1><p>Every change is recorded. The physical board remains the source of movement; this is the source of game state.</p></div><button class="btn ${state.running?'danger':'green'}" onclick="toggleTimer()">${state.running?'Pause match':'Start 50-minute match'}</button></div>${metrics()}<div class="admin-layout" style="margin-top:16px"><div class="admin-main"><div class="panel"><div class="section-head"><div><h2>Live scoreboard</h2><p>Tap a team to open its controls.</p></div><span class="status-pill">${state.phase==='finished'?'Frozen':'Round robin'}</span></div><div class="team-table-wrap"><table class="team-table"><thead><tr><th>Team</th><th>Cash</th><th>Company value</th><th>Businesses</th><th>Board</th></tr></thead><tbody>${teams.slice(0,state.teamCount).map((t,i)=>`<tr class="${state.selectedTeam===i?'selected':''}" onclick="selectTeam(${i})"><td>${team(t)}</td><td class="cash">${money(t.cash)}</td><td class="cv">${t.cv.toLocaleString('en-IN')}</td><td>${t.businesses.length} / 3</td><td>Space ${t.pos+1}</td></tr>`).join('')}</tbody></table></div></div><div class="panel"><div class="section-head"><div><h2>24-space board</h2><p>Movement is resolved one landing at a time.</p></div><span class="muted">Turn ${state.activeTeam+1}</span></div><div class="board">${spaces.map((s,i)=>`<div class="space ${s==='START'?'start':''} ${s.includes('Card')?'card':''} ${s==='Wildcard'?'wild':''} ${s.startsWith('Action')||s.startsWith('Pitch')?'action':''}"><span class="space-no">${i+1}</span><strong>${s}</strong></div>`).join('')}</div></div></div><aside class="side-stack">${adminControls()}<div class="panel"><div class="section-head"><div><h3>Activity log</h3><p>Newest first</p></div></div><div class="log">${state.logs.slice().reverse().map(l=>`<div class="log-row"><span class="log-time">${l[0]}</span><span>${l[1]}</span></div>`).join('')}</div></div></aside></div></main></div>`; }
function adminControls(){ const t=teams[state.selectedTeam], active=teams[state.activeTeam], p=state.pendingLanding; return `<div class="panel"><div class="eyebrow">Selected team</div><h2>${t.name}</h2><p class="muted">${t.businesses.length} businesses · position ${t.pos+1}</p><div class="grid grid-2"><div class="metric" style="padding:12px 0"><div class="label">Cash</div><div class="value cash" style="font-size:22px">${money(t.cash)}</div></div><div class="metric" style="padding:12px 0"><div class="label">Company value</div><div class="value cv" style="font-size:22px">${t.cv}</div></div></div>${p?landingPanel(p):`<label class="muted" style="font-size:12px">Manual adjustment</label><div class="actions" style="margin-top:8px"><button class="action-btn" onclick="changeCash(100)">+ ₹100<small>Cash reward</small></button><button class="action-btn" onclick="changeCash(-100)">− ₹100<small>Cash penalty</small></button><button class="action-btn" onclick="changeCv(200)">+ 200 CV<small>Company value</small></button><button class="action-btn" onclick="changeCv(-200)">− 200 CV<small>Company value</small></button></div>`}<div style="display:grid;gap:9px;margin-top:12px"><button class="btn primary" ${p?'disabled':''} onclick="roll()">Roll die · ${active.name}</button><button class="btn" ${p?'disabled':''} onclick="cycleTurn()">End turn → next team</button><button class="btn danger" onclick="finishMatch()">Freeze scoreboard & calculate winner</button><button class="btn ghost" onclick="resetMatch()">Reset for next match</button></div><div style="margin-top:16px"><label class="muted" style="font-size:12px">Businesses owned</label><div class="business-list" style="margin-top:8px">${t.businesses.length?t.businesses.map(id=>{const b=businesses[id];return `<div class="business-row"><div>${b.name}<small>Level ${b.level} · ${money(b.cost)}</small></div><span class="level">${b.level===2?'MAX':'UPGRADE'}</span></div>`}).join(''):'<p class="muted" style="font-size:13px;margin:8px 0 0">No businesses yet.</p>'}</div></div></div>`; }
function landingPanel(p){ if(state.pendingSale)return forcedSalePanel(); const t=teams[p.teamIndex], s=spaces[p.spaceIndex], bid=businesses.findIndex(b=>b.name===s), b=bid>=0?businesses[bid]:null; let body=''; if(b){ const owner=b.owner===null?'Available':teams[b.owner].name; if(b.owner===null) body=`<p class="muted">${b.name} · landing ${p.spaceIndex+1}</p><div class="privacy-note" style="margin:10px 0">Owner: <strong>${owner}</strong><br>Roll: <strong>${p.roll}</strong></div><button class="btn green" ${t.businesses.length>=3||t.cash<b.cost?'disabled':''} onclick="buyBusiness(${bid})">Buy for ${money(b.cost)}</button>`; else if(b.owner===p.teamIndex) body=`<p class="muted">${b.name} · landing ${p.spaceIndex+1}</p><div class="privacy-note" style="margin:10px 0">Owner: <strong>${owner}</strong><br>Roll: <strong>${p.roll}</strong></div><button class="btn primary" ${b.level>=2?'disabled':''} onclick="upgradeBusiness(${bid})">Upgrade for ${money(upgradeCost(b))}</button>`; else body=`<p class="muted">${b.name} · landing ${p.spaceIndex+1}</p><div class="privacy-note" style="margin:10px 0">Owner: <strong>${owner}</strong><br>Roll: <strong>${p.roll}</strong></div><button class="btn primary" onclick="payRent(${bid})">Resolve rent · ${money(rent(b))}</button>`; } else if(s.includes('Bonus')||s.includes('Crisis')) body=cardPanel(p,s); else body=`<p class="muted">${s} · landing ${p.spaceIndex+1} · roll ${p.roll}</p><div class="privacy-note" style="margin:10px 0">Resolve the physical station/action, then confirm it here so the audit log stays complete.</div><button class="btn green" onclick="confirmLanding()">Confirm ${s}</button>`; return `<div class="privacy-note" style="margin:12px 0 0;border-color:rgba(255,200,87,.3);background:rgba(255,200,87,.08);color:#fff0c5"><strong>Pending landing</strong><br>${body}</div>`; }
function cardPanel(p,s){ const t=teams[p.teamIndex], card=p.roll, isBonus=s.includes('Bonus'), bonus=['Startup Grant','Viral Growth','Government Incentive','Premium Deal','Founder Bonus','Lucky Break'], crisis=['Tax Raid','Market Crash','Legal Trouble','Burn Rate Spike','Bad PR','Investor Pullout'], name=(isBonus?bonus:crisis)[card-1]||'Card'; return `<p class="muted">${s} · Card #${card}</p><div class="privacy-note" style="margin:10px 0">${name}<br><span class="muted">${isBonus?bonusText(card,t):crisisText(card,t)}</span></div><button class="btn green" onclick="resolveCard(${isBonus?'true':'false'},${card})">Apply ${name}</button>`; }
function bonusText(n,t){return ['+₹300 cash','+300 Company Value','+₹200 cash + 200 Company Value',`Cash equal to the most expensive owned business${t.businesses.length?'':' (₹0)'}`,`₹100 × ${t.businesses.length} businesses`,'Roll again for a cash reward'][n-1];}
function crisisText(n,t){return ['−₹300 cash','−300 Company Value','−₹200 cash −200 Company Value',`−₹100 × ${t.businesses.length} businesses`,'−200 Company Value −₹100 cash','−₹500 cash'][n-1];}
function forcedSalePanel(){ const s=state.pendingSale, t=teams[s.teamIndex]; return `<div class="privacy-note" style="margin:12px 0 0;border-color:rgba(255,102,123,.42);background:rgba(255,102,123,.09);color:#ffe1e5"><strong>Forced sale required</strong><br>${t.name} has ${money(t.cash)} and owes ${money(s.amount)}. Cash is applied first; choose a business to sell for its original purchase cost.</div><div class="business-list" style="margin-top:9px">${t.businesses.map(id=>{const b=businesses[id];return `<button class="business-row" style="border:1px solid rgba(255,102,123,.25);color:var(--ink);text-align:left" onclick="sellBusiness(${id})"><span><strong>Sell ${b.name}</strong><small>Receive ${money(b.cost)} · upgrades lost · earned CV stays</small></span><span class="level">SELL</span></button>`}).join('')}</div>`; }
function player(){ const t=teams[state.selectedPlayer]; return `<div class="app-shell">${header()}<main class="content player-layout"><div class="player-header"><div><div class="eyebrow">Player dashboard · Live</div><div class="player-team-title"><i class="big-dot" style="background:${t.color}"></i><h1 style="margin:6px 0 0">${t.name}</h1></div><p class="muted">Your team view. Other teams’ private numbers are intentionally hidden.</p></div><select class="select" style="max-width:180px" onchange="state.selectedPlayer=+this.value;app()">${teams.slice(0,state.teamCount).map((x,i)=>`<option value="${i}" ${i===state.selectedPlayer?'selected':''}>${x.name} · demo</option>`).join('')}</select></div><div class="privacy-note" style="margin-bottom:16px">Match clock <strong style="float:right;color:var(--green)">${clock()}</strong><br><span class="muted">The Game Master is currently resolving ${teams[state.activeTeam].name}’s turn.</span></div><div class="grid grid-3"><div class="panel metric big-stat"><div class="label">Your cash</div><div class="value cash">${money(t.cash)}</div><span class="muted">Available to buy and pay</span></div><div class="panel metric big-stat"><div class="label">Company value</div><div class="value cv">${t.cv.toLocaleString('en-IN')}</div><span class="muted">Highest wins at 50:00</span></div><div class="panel metric big-stat"><div class="label">Businesses</div><div class="value">${t.businesses.length}<span class="muted" style="font-size:18px"> / 3</span></div><span class="muted">Maximum portfolio</span></div></div><div class="grid grid-2" style="margin-top:16px"><div class="panel"><div class="section-head"><div><h2>Your portfolio</h2><p>Upgrades increase rent and landing value.</p></div></div><div class="business-list">${t.businesses.length?t.businesses.map(id=>{const b=businesses[id];return `<div class="business-row"><div><strong>${b.name}</strong><small>Base ${money(b.cost)} · upgrade level ${b.level}</small></div><span class="level">${b.level===2?'MAXED':`U${b.level}`}</span></div>`}).join(''):'<p class="muted">No businesses owned yet. Your next landing could change that.</p>'}</div></div><div class="panel"><div class="section-head"><div><h2>Live events</h2><p>Only events relevant to your team appear here.</p></div></div><div class="event-card"><div class="event-icon">✦</div><div><h3>Match is live</h3><p>Follow the physical token and wait for the admin to confirm your landing. Payments, cards and upgrades will appear here.</p></div></div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><div class="event-card"><div class="event-icon">↗</div><div><h3>Next turn order</h3><p>${teams[(state.activeTeam+1)%state.teamCount].name} follows ${teams[state.activeTeam].name} in the round-robin.</p></div></div></div></div></main><nav class="bottom-nav"><button class="active">Overview</button><button>Portfolio</button><button>Rules</button></nav></div>`; }
function log(msg){ const now=new Date(); state.logs.push([now.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}),msg]); }
function startSetup(){state.screen='setup';app();}
function beginMatch(){state.screen='admin';state.phase='live';log('All six teams checked in. Match moved to the physical board.');app();}
function openPlayer(){state.screen='player';app();}
function goHome(){state.screen='home';state.running=false;app();}
function selectTeam(i){state.selectedTeam=i;app();}
function changeCash(n){const t=teams[state.selectedTeam];t.cash+=n;log(`${t.name}: ${n>0?'+':''}${money(n)} cash adjustment.`);app();toast('Cash updated and recorded');}
function changeCv(n){const t=teams[state.selectedTeam];t.cv=Math.max(0,t.cv+n);log(`${t.name}: ${n>0?'+':''}${n} Company Value.`);app();toast('Company value updated');}
function upgradeCost(b){return ({200:150,300:200,400:250,500:300}[b.cost]||200)+(b.level===1?({200:50,300:50,400:50,500:50}[b.cost]||50):0);}
function rent(b){return Math.round(b.cost*([.5,.75,1][b.level]||.5));}
function landedTeam(){return teams[state.pendingLanding.teamIndex];}
function finishLanding(message){const p=state.pendingLanding;log(message);state.pendingLanding=null;if(p.roll===6){app();toast('Landing resolved — extra roll granted');}else cycleTurn();}
function buyBusiness(bid){const b=businesses[bid],t=landedTeam();if(b.owner!==null||t.businesses.length>=3||t.cash<b.cost)return;t.cash-=b.cost;t.cv+=b.baseCv;t.businesses.push(bid);b.owner=state.activeTeam;finishLanding(`${t.name} bought ${b.name} for ${money(b.cost)} and received ${b.baseCv} CV.`);}
function upgradeBusiness(bid){const b=businesses[bid],t=landedTeam(),cost=upgradeCost(b);if(b.owner!==state.activeTeam||b.level>=2||t.cash<cost)return;t.cash-=cost;b.level+=1;t.cv+=b.level===1?300:400;finishLanding(`${t.name} upgraded ${b.name} to Level ${b.level} for ${money(cost)}.`);}
function payRent(bid){const b=businesses[bid],payer=landedTeam(),owner=teams[b.owner],amount=rent(b);if(payer.cash<amount){const cashApplied=payer.cash;payer.cash=0;state.pendingSale={teamIndex:state.activeTeam,amount:amount-cashApplied,ownerIndex:b.owner,bid};log(`${payer.name} applied ${money(cashApplied)} cash and still owes ${money(amount-cashApplied)} rent to ${owner.name}; forced sale required.`);app();toast('Insufficient cash — choose a business to sell');return;}payer.cash-=amount;owner.cash+=amount;owner.cv+=Math.round(b.baseCv*([.5,.75,1][b.level]||.5));finishLanding(`${payer.name} paid ${money(amount)} rent to ${owner.name} on ${b.name}.`);}
function sellBusiness(bid){const sale=state.pendingSale;if(!sale)return;const t=teams[sale.teamIndex],b=businesses[bid];if(b.owner!==sale.teamIndex)return;t.cash+=b.cost;t.businesses=t.businesses.filter(id=>id!==bid);b.owner=null;b.level=0;if(t.cash<sale.amount){const remaining=sale.amount-t.cash;t.cash=0;state.pendingSale={...sale,amount:remaining};if(t.businesses.length===0){log(`${t.name} cannot cover the remaining ${money(remaining)} and is bankrupt.`);finishBankruptcy(t);return;}log(`${t.name} sold ${b.name}; ${money(remaining)} remains due.`);app();toast(`Still owes ${money(remaining)}`);return;}t.cash-=sale.amount;teams[sale.ownerIndex].cash+=sale.amount;state.pendingSale=null;finishLanding(`${t.name} sold ${b.name}, paid the rent and retained earned CV.`);}
function finishBankruptcy(t){t.cash=0;t.businesses.slice().forEach(id=>{businesses[id].owner=null;businesses[id].level=0;});t.businesses=[];state.pendingSale=null;state.pendingLanding=null;log(`${t.name} eliminated from the match through bankruptcy.`);cycleTurn();}
function resolveCard(isBonus,n){const t=landedTeam();if(isBonus){if(n===1)t.cash+=300;if(n===2)t.cv+=300;if(n===3){t.cash+=200;t.cv+=200;}if(n===4)t.cash+=t.businesses.reduce((m,id)=>Math.max(m,businesses[id].cost),0);if(n===5)t.cash+=100*t.businesses.length;if(n===6){const reward=Math.floor(Math.random()*6)+1;t.cash+=100*reward;log(`${t.name} received Lucky Break reward roll ${reward}.`);}}else{if(n===1)t.cash=Math.max(0,t.cash-300);if(n===2)t.cv=Math.max(0,t.cv-300);if(n===3){t.cash=Math.max(0,t.cash-200);t.cv=Math.max(0,t.cv-200);}if(n===4)t.cash=Math.max(0,t.cash-100*t.businesses.length);if(n===5){t.cv=Math.max(0,t.cv-200);t.cash=Math.max(0,t.cash-100);}if(n===6)t.cash=Math.max(0,t.cash-500);}const card=(isBonus?['Startup Grant','Viral Growth','Government Incentive','Premium Deal','Founder Bonus','Lucky Break']:['Tax Raid','Market Crash','Legal Trouble','Burn Rate Spike','Bad PR','Investor Pullout'])[n-1];finishLanding(`${t.name} resolved ${card}.`);}
function confirmLanding(){const p=state.pendingLanding,t=landedTeam(),s=spaces[p.spaceIndex];if(s==='START'){t.cash+=200;log(`${t.name} crossed START: +₹200 cash.`);}else if(s.includes('Crisis')){t.cash=Math.max(0,t.cash-100);log(`${t.name} resolved a Crisis card: −₹100 cash (admin can edit exact card effect).`);}else if(s.includes('Bonus')){t.cash+=100;log(`${t.name} resolved a Bonus card: +₹100 cash (admin can edit exact card effect).`);}else if(s==='Action C'){t.cv=Math.max(0,t.cv-200);log(`${t.name} resolved Lose the Feature: −200 CV.`);}else if(s==='Action D'){log(`${t.name} resolved Steal Talent at Action D.`);}else if(s==='Action B'||s==='Pitch to Investors'){log(`${t.name} completed the investor pitch action.`);}else if(s==='Wildcard'){log(`${t.name} completed a Wildcard challenge.`);}finishLanding(`${t.name} completed ${s}.`);}
function resetMatch(){teams.forEach(t=>{t.cash=1000;t.cv=0;t.pos=0;t.businesses=[];});businesses.forEach(b=>{b.owner=null;b.level=0;});state.seconds=3000;state.running=false;state.phase='waiting';state.activeTeam=0;state.selectedTeam=0;state.pendingLanding=null;state.pendingSale=null;state.turnRolls=0;state.logs=[['09:00','New match reset. All teams restored to ₹1,000.']];state.screen='setup';app();}
function cycleTurn(){state.activeTeam=(state.activeTeam+1)%state.teamCount;state.turnRolls=0;state.turnStartPos=teams[state.activeTeam].pos;log(`Turn passed to ${teams[state.activeTeam].name}.`);app();}
function roll(){if(state.pendingLanding)return;const n=Math.floor(Math.random()*6)+1,t=teams[state.activeTeam];if(state.turnRolls===0)state.turnStartPos=t.pos;state.turnRolls++;t.pos=(t.pos+n)%24;if(n===6&&state.turnRolls===3){t.pos=state.turnStartPos;state.turnRolls=0;log(`${t.name} rolled three 6s. Turn cancelled and position restored.`);cycleTurn();toast('Three 6s — turn cancelled');return;}state.pendingLanding={teamIndex:state.activeTeam,spaceIndex:t.pos,roll:n};log(`${t.name} rolled ${n} and moved to space ${t.pos+1}. Landing requires resolution.`);app();toast(`Rolled ${n}${n===6?' — resolve, then extra roll':''}`);}
function toggleTimer(){state.running=!state.running;app();}
function finishMatch(){state.running=false;state.phase='finished';const winner=[...teams].sort((a,b)=>b.cv-a.cv||b.cash-a.cash||b.businesses.length-a.businesses.length)[0];log(`Scoreboard frozen. ${winner.name} wins on Company Value.`);app();toast(`${winner.name} is the current winner`);}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2400);}
setInterval(()=>{if(state.running&&state.seconds>0){state.seconds--;const c=$('#clock');if(c)c.textContent=clock();}},1000);
app();
