import { BoardSpace } from '../types/game';

export const BOARD_SPACES: BoardSpace[] = [
  {
    index: 0,
    name: 'START',
    type: 'start',
    description: 'Collect ₹200 cash. Portfolio Growth: +0 CV (0-1 biz), +200 CV (2 biz), +500 CV (3 biz).',
  },
  {
    index: 1,
    name: 'Pitch to Investors',
    type: 'action_b',
    description: 'If you own ≥1 business, pitch it to the Game Master. Fail = lose next turn.',
  },
  {
    index: 2,
    name: 'EdTech',
    type: 'business',
    businessId: 0,
    description: 'Cost: ₹200 | Initial CV: +150 | Category: Education',
  },
  {
    index: 3,
    name: 'Bonus Card',
    type: 'bonus',
    description: 'Movement roll determines Bonus Card (1–6). Startup grants, viral growth & perks.',
  },
  {
    index: 4,
    name: 'SaaS',
    type: 'business',
    businessId: 1,
    description: 'Cost: ₹300 | Initial CV: +180 | Category: Cloud Software',
  },
  {
    index: 5,
    name: 'Crisis Card',
    type: 'crisis',
    description: 'Movement roll determines Crisis Card (1–6). Tax audits, market crash & penalties.',
  },
  {
    index: 6,
    name: 'E-Commerce',
    type: 'business',
    businessId: 2,
    description: 'Cost: ₹300 | Initial CV: +180 | Category: Marketplaces',
  },
  {
    index: 7,
    name: 'Action C: Lose Feature',
    type: 'action_c',
    description: 'Product regression: Lose 200 Company Value immediately (CV minimum remains 0).',
  },
  {
    index: 8,
    name: 'FinTech',
    type: 'business',
    businessId: 3,
    description: 'Cost: ₹400 | Initial CV: +200 | Category: Payments',
  },
  {
    index: 9,
    name: 'Wildcard',
    type: 'wildcard',
    description: 'Physical & social summit challenge assigned by the Game Master.',
  },
  {
    index: 10,
    name: 'HealthTech',
    type: 'business',
    businessId: 4,
    description: 'Cost: ₹400 | Initial CV: +200 | Category: Biotech',
  },
  {
    index: 11,
    name: 'Bonus Card',
    type: 'bonus',
    description: 'Movement roll determines Bonus Card (1–6).',
  },
  {
    index: 12,
    name: 'AI / DeepTech',
    type: 'business',
    businessId: 5,
    description: 'Cost: ₹500 | Initial CV: +250 | Category: AI Systems',
  },
  {
    index: 13,
    name: 'Action D: Steal Talent',
    type: 'action_d',
    description: 'Choose a competitor team to poach talent: Transfer up to ₹100 cash to your balance.',
  },
  {
    index: 14,
    name: 'DevTools / Infra',
    type: 'business',
    businessId: 6,
    description: 'Cost: ₹300 | Initial CV: +190 | Category: Developer Tools',
  },
  {
    index: 15,
    name: 'Crisis Card',
    type: 'crisis',
    description: 'Movement roll determines Crisis Card (1–6).',
  },
  {
    index: 16,
    name: 'Cybersecurity',
    type: 'business',
    businessId: 7,
    description: 'Cost: ₹400 | Initial CV: +220 | Category: Security',
  },
  {
    index: 17,
    name: 'Bonus Card',
    type: 'bonus',
    description: 'Movement roll determines Bonus Card (1–6).',
  },
  {
    index: 18,
    name: 'CleanTech / Energy',
    type: 'business',
    businessId: 8,
    description: 'Cost: ₹500 | Initial CV: +240 | Category: Clean Tech',
  },
  {
    index: 19,
    name: 'Pitch to Investors',
    type: 'action_b',
    description: 'If you own ≥1 business, pitch it to the Game Master. Fail = lose next turn.',
  },
  {
    index: 20,
    name: 'Robotics & IoT',
    type: 'business',
    businessId: 9,
    description: 'Cost: ₹500 | Initial CV: +250 | Category: Hardware & IoT',
  },
  {
    index: 21,
    name: 'Crisis Card',
    type: 'crisis',
    description: 'Movement roll determines Crisis Card (1–6).',
  },
  {
    index: 22,
    name: 'Wildcard',
    type: 'wildcard',
    description: 'Physical & social summit challenge assigned by the Game Master.',
  },
  {
    index: 23,
    name: 'Bonus Card',
    type: 'bonus',
    description: 'Movement roll determines Bonus Card (1–6).',
  },
];
